spring:
  application:
    name: gmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: mplane.cn:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://gmall-product
          predicates:
            - Path=/admin/product/**
          filters:
            - RewritePath=/admin/product/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://gmall-admin
          predicates:
            - Path=/admin/**



server:
  port: 88

