spring:
  application:
    name: gmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: mplane.cn:8848
        ip: 127.0.0.1
    gateway:
      routes:
        - id: product_route
          uri: lb://gmall-product
          predicates:
            - Path=/admin/product/**
          filters:
            - RewritePath=/admin/product/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://gmall-member
          predicates:
            - Path=/admin/member/**
          filters:
            - RewritePath=/admin/member/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://gmall-ware
          predicates:
            - Path=/admin/ware/**
          filters:
            - RewritePath=/admin/ware/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://gmall-admin
          predicates:
            - Path=/admin/**



server:
  port: 88

