spring:
  datasource:
    username: root
    password: 28Z3Vay5
    url: jdbc:mysql://120.79.17.186:3306/gmall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: gmall-product
  cloud:
    nacos:
      discovery:
        server-addr: mplane.cn:8848
  redis:
    host: mplane.cn
    database: 0
    port: 6379
    password: xxx123





mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 10000
fdfs:
  connect-timeout: 6000
  so-timeout: 1500
  tracker-list:
    - static.otcrmbt.com:22122
  pool:
    #从池中借出的对象的最大数目
    max-total: 153
    max-wait-millis: 102
    jmx-name-base: 1
    jmx-name-prefix: 1
  web-server-url: http://static.otcrmbt.com:18080/
