spring:
  datasource:
    username: root
    password: xxx123
    url: jdbc:mysql://mplane.cn:3306/gmall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: gmall-product
  cloud:
    nacos:
      discovery:
        server-addr: mplane.cn:8848


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 10000
