spring:
  datasource:
    username: root
    password: 28Z3Vay5
    url: jdbc:mysql://120.79.17.186:3306/gmall_wms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: gmall-ware
  cloud:
    nacos:
      discovery:
        server-addr: mplane.cn:8848


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000

